//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://shovell.red-gate.com/")]
public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback AllArticlesOperationCompleted;
    
    private System.Threading.SendOrPostCallback SubmitArticleOperationCompleted;
    
    /// <remarks/>
    public WebService() {
        this.Url = "http://localhost/shovell/webservice.asmx";
    }
    
    /// <remarks/>
    public event AllArticlesCompletedEventHandler AllArticlesCompleted;
    
    /// <remarks/>
    public event SubmitArticleCompletedEventHandler SubmitArticleCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://shovell.red-gate.com/AllArticles", RequestNamespace="http://shovell.red-gate.com/", ResponseNamespace="http://shovell.red-gate.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Article[] AllArticles() {
        object[] results = this.Invoke("AllArticles", new object[0]);
        return ((Article[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAllArticles(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AllArticles", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public Article[] EndAllArticles(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Article[])(results[0]));
    }
    
    /// <remarks/>
    public void AllArticlesAsync() {
        this.AllArticlesAsync(null);
    }
    
    /// <remarks/>
    public void AllArticlesAsync(object userState) {
        if ((this.AllArticlesOperationCompleted == null)) {
            this.AllArticlesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllArticlesOperationCompleted);
        }
        this.InvokeAsync("AllArticles", new object[0], this.AllArticlesOperationCompleted, userState);
    }
    
    private void OnAllArticlesOperationCompleted(object arg) {
        if ((this.AllArticlesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AllArticlesCompleted(this, new AllArticlesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://shovell.red-gate.com/SubmitArticle", RequestNamespace="http://shovell.red-gate.com/", ResponseNamespace="http://shovell.red-gate.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SubmitArticle(string username, string password, string title, string contents, string parent) {
        this.Invoke("SubmitArticle", new object[] {
                    username,
                    password,
                    title,
                    contents,
                    parent});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSubmitArticle(string username, string password, string title, string contents, string parent, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SubmitArticle", new object[] {
                    username,
                    password,
                    title,
                    contents,
                    parent}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSubmitArticle(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SubmitArticleAsync(string username, string password, string title, string contents, string parent) {
        this.SubmitArticleAsync(username, password, title, contents, parent, null);
    }
    
    /// <remarks/>
    public void SubmitArticleAsync(string username, string password, string title, string contents, string parent, object userState) {
        if ((this.SubmitArticleOperationCompleted == null)) {
            this.SubmitArticleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitArticleOperationCompleted);
        }
        this.InvokeAsync("SubmitArticle", new object[] {
                    username,
                    password,
                    title,
                    contents,
                    parent}, this.SubmitArticleOperationCompleted, userState);
    }
    
    private void OnSubmitArticleOperationCompleted(object arg) {
        if ((this.SubmitArticleCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SubmitArticleCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://shovell.red-gate.com/")]
public partial class Article {
    
    private string uidField;
    
    private string authorField;
    
    private System.DateTime timeField;
    
    private string titleField;
    
    private string contentsField;
    
    private string parentField;
    
    private int votesField;
    
    /// <remarks/>
    public string Uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
    
    /// <remarks/>
    public string Author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string Contents {
        get {
            return this.contentsField;
        }
        set {
            this.contentsField = value;
        }
    }
    
    /// <remarks/>
    public string Parent {
        get {
            return this.parentField;
        }
        set {
            this.parentField = value;
        }
    }
    
    /// <remarks/>
    public int Votes {
        get {
            return this.votesField;
        }
        set {
            this.votesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void AllArticlesCompletedEventHandler(object sender, AllArticlesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AllArticlesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal AllArticlesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Article[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Article[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void SubmitArticleCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
