//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "SolarSystem")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "SolarSystem", IsNullable = false)]
public partial class SolarSystem
{

    private SolarSystemPlanets[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Planets")]
    public SolarSystemPlanets[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "SolarSystem")]
public partial class SolarSystemPlanets
{

    private SolarSystemPlanetsPlanet[] planetField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Planet")]
    public SolarSystemPlanetsPlanet[] Planet
    {
        get
        {
            return this.planetField;
        }
        set
        {
            this.planetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "SolarSystem")]
public partial class SolarSystemPlanetsPlanet
{

    private SolarSystemPlanetsPlanetSatellitesSatellite[] satellitesField;

    private string nameField;

    private string distanceToSunField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Satellite", typeof(SolarSystemPlanetsPlanetSatellitesSatellite), IsNullable = false)]
    public SolarSystemPlanetsPlanetSatellitesSatellite[] Satellites
    {
        get
        {
            return this.satellitesField;
        }
        set
        {
            this.satellitesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string distanceToSun
    {
        get
        {
            return this.distanceToSunField;
        }
        set
        {
            this.distanceToSunField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "SolarSystem")]
public partial class SolarSystemPlanetsPlanetSatellitesSatellite
{

    private string nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}
