<%@ Page Language="C#" MasterPageFile="~/Views/Shared/Site.Master" Inherits="System.Web.Mvc.ViewPage" %>

<asp:Content ID="Content1" ContentPlaceHolderID="TitleContent" runat="server">
    Home Page
</asp:Content>
<asp:Content ID="headContent" ContentPlaceHolderID="CustomHeadContent" runat="server">
    <script type="text/javascript">


        $("document").ready(function () { cornersHome(); });
        function cornersHome() {
            $(".displayContainerInnerHome").corner("bevel tl 30px").corner("bevel tr 6px").corner("bevel bottom 6px").parent().css('padding', '6px').corner("round keep tl 20px").corner("round keep tr 12px").corner("round keep bottom 12px");
        }

        
    </script>

       <style type="text/css">
.live-support-start {
	-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
	-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
	box-shadow:inset 0px 1px 0px 0px #ffffff;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );
	background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf');
	background-color:#ededed;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #000000;
	display:inline-block;
	color:#777777;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #ffffff;
}.live-support-start:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) );
	background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed');
	background-color:#dfdfdf;
}.live-support-start:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>
</asp:Content>
<asp:Content ID="mainContent" ContentPlaceHolderID="MainContent" runat="server">
    <div style="max-width:1000px;margin: auto;">
        <div class="contentContainer">
            <div class="displayContainerOuterHome">
                <div class="displayContainerInnerHome">
                    <table cellpadding="0" cellspacing="0" style="width: 100%;">
                        <tbody>
                            <tr>
                                <td style="vertical-align: top; background-color: #fff;">
                                    <div style="padding: 10px;">
                                        <h2>
                                            Welcome to your IT Services support forum</h2>
                                        <p>
                                            Please login to register a ticket or check on an existing ticket's status.
                                        </p>
                                        <p>
                                            Alternatively, if you require assistance urgently, you may prefer to use the live chat system.
                                        </p>
                                    </div>
                                    <div class="clear">
                                    </div>
                                </td>
                                <td style="width:250px; vertical-align: top; padding: 0px;
                                    border-left: solid 1px #B3CBDF;">
                                    <div style="float: left;">
                                        <div style="padding: 8px;">
                                        
                                            <div style="-moz-border-radius: 15px;border-radius: 15px;height:170px;width:350px;background:url('<%= Url.Content("~/Content/james.png")%>') no-repeat bottom right #B3CBDF;padding:20px;">
                                               <h3 style="margin-top:0;">Need support <span style="font-style:italic;">right now</span>?</h3>
                                               <h4>There are <%= ViewData["onlineEngineers"] %> engineers online.</h4>
                                                <a id="live-support-request" style="-moz-transition: none; -webkit-transition: none; transition:none;" href="/Home/LiveHelp" class="live-support-start">Request Live Support</a>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</asp:Content>