// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace TicketDesk.Web.Client.Areas.Admin.Controllers
{
    public partial class SecurityManagementController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SecurityManagementController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetUserByEmailAddress()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetUserByEmailAddress);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SecurityManagementController Actions { get { return MVC.Admin.SecurityManagement; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "SecurityManagement";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "SecurityManagement";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string UsersList = "UsersList";
            public readonly string EditUser = "EditUser";
            public readonly string CreateUser = "CreateUser";
            public readonly string DeleteUser = "DeleteUser";
            public readonly string RolesList = "RolesList";
            public readonly string GetUserByEmailAddress = "GetUserByEmailAddress";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string UsersList = "UsersList";
            public const string EditUser = "EditUser";
            public const string CreateUser = "CreateUser";
            public const string DeleteUser = "DeleteUser";
            public const string RolesList = "RolesList";
            public const string GetUserByEmailAddress = "GetUserByEmailAddress";
        }


        static readonly ActionParamsClass_UsersList s_params_UsersList = new ActionParamsClass_UsersList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UsersList UsersListParams { get { return s_params_UsersList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UsersList
        {
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_EditUser s_params_EditUser = new ActionParamsClass_EditUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditUser EditUserParams { get { return s_params_EditUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditUser
        {
            public readonly string userName = "userName";
            public readonly string user = "user";
        }
        static readonly ActionParamsClass_CreateUser s_params_CreateUser = new ActionParamsClass_CreateUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateUser CreateUserParams { get { return s_params_CreateUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateUser
        {
            public readonly string user = "user";
        }
        static readonly ActionParamsClass_DeleteUser s_params_DeleteUser = new ActionParamsClass_DeleteUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteUser DeleteUserParams { get { return s_params_DeleteUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteUser
        {
            public readonly string userName = "userName";
            public readonly string user = "user";
        }
        static readonly ActionParamsClass_GetUserByEmailAddress s_params_GetUserByEmailAddress = new ActionParamsClass_GetUserByEmailAddress();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetUserByEmailAddress GetUserByEmailAddressParams { get { return s_params_GetUserByEmailAddress; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetUserByEmailAddress
        {
            public readonly string emailAddress = "emailAddress";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string CreateUser = "CreateUser";
                public readonly string DeleteUser = "DeleteUser";
                public readonly string EditUser = "EditUser";
                public readonly string Index = "Index";
                public readonly string UsersList = "UsersList";
            }
            public readonly string CreateUser = "~/Areas/Admin/Views/SecurityManagement/CreateUser.aspx";
            public readonly string DeleteUser = "~/Areas/Admin/Views/SecurityManagement/DeleteUser.aspx";
            public readonly string EditUser = "~/Areas/Admin/Views/SecurityManagement/EditUser.aspx";
            public readonly string Index = "~/Areas/Admin/Views/SecurityManagement/Index.aspx";
            public readonly string UsersList = "~/Areas/Admin/Views/SecurityManagement/UsersList.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SecurityManagementController : TicketDesk.Web.Client.Areas.Admin.Controllers.SecurityManagementController
    {
        public T4MVC_SecurityManagementController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void UsersListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page);

        public override System.Web.Mvc.ActionResult UsersList(int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UsersList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            UsersListOverride(callInfo, page);
            return callInfo;
        }

        partial void EditUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string userName);

        public override System.Web.Mvc.ActionResult EditUser(string userName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userName", userName);
            EditUserOverride(callInfo, userName);
            return callInfo;
        }

        partial void EditUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, TicketDesk.Web.Client.Areas.Admin.Models.SecurityManagementUserViewModel user);

        public override System.Web.Mvc.ActionResult EditUser(TicketDesk.Web.Client.Areas.Admin.Models.SecurityManagementUserViewModel user)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "user", user);
            EditUserOverride(callInfo, user);
            return callInfo;
        }

        partial void CreateUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult CreateUser()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateUser);
            CreateUserOverride(callInfo);
            return callInfo;
        }

        partial void CreateUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, TicketDesk.Web.Client.Areas.Admin.Models.SecurityManagementUserViewModel user);

        public override System.Web.Mvc.ActionResult CreateUser(TicketDesk.Web.Client.Areas.Admin.Models.SecurityManagementUserViewModel user)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "user", user);
            CreateUserOverride(callInfo, user);
            return callInfo;
        }

        partial void DeleteUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string userName);

        public override System.Web.Mvc.ActionResult DeleteUser(string userName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userName", userName);
            DeleteUserOverride(callInfo, userName);
            return callInfo;
        }

        partial void DeleteUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, TicketDesk.Web.Client.Areas.Admin.Models.SecurityManagementUserViewModel user);

        public override System.Web.Mvc.ActionResult DeleteUser(TicketDesk.Web.Client.Areas.Admin.Models.SecurityManagementUserViewModel user)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "user", user);
            DeleteUserOverride(callInfo, user);
            return callInfo;
        }

        partial void RolesListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult RolesList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RolesList);
            RolesListOverride(callInfo);
            return callInfo;
        }

        partial void GetUserByEmailAddressOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string emailAddress);

        public override System.Web.Mvc.ActionResult GetUserByEmailAddress(string emailAddress)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetUserByEmailAddress);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "emailAddress", emailAddress);
            GetUserByEmailAddressOverride(callInfo, emailAddress);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
