// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace TicketDesk.Web.Client.Areas.Admin.Controllers
{
    public partial class EmailTemplateController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected EmailTemplateController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DisplayHtml()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DisplayHtml);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DisplayOutlookHtml()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DisplayOutlookHtml);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DisplayText()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DisplayText);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public EmailTemplateController Actions { get { return MVC.Admin.EmailTemplate; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "EmailTemplate";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "EmailTemplate";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string ProcessWaitingNotesNow = "ProcessWaitingNotesNow";
            public readonly string DisplayHtml = "DisplayHtml";
            public readonly string DisplayOutlookHtml = "DisplayOutlookHtml";
            public readonly string DisplayText = "DisplayText";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string ProcessWaitingNotesNow = "ProcessWaitingNotesNow";
            public const string DisplayHtml = "DisplayHtml";
            public const string DisplayOutlookHtml = "DisplayOutlookHtml";
            public const string DisplayText = "DisplayText";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string id = "id";
            public readonly string mode = "mode";
        }
        static readonly ActionParamsClass_DisplayHtml s_params_DisplayHtml = new ActionParamsClass_DisplayHtml();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DisplayHtml DisplayHtmlParams { get { return s_params_DisplayHtml; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DisplayHtml
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DisplayOutlookHtml s_params_DisplayOutlookHtml = new ActionParamsClass_DisplayOutlookHtml();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DisplayOutlookHtml DisplayOutlookHtmlParams { get { return s_params_DisplayOutlookHtml; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DisplayOutlookHtml
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DisplayText s_params_DisplayText = new ActionParamsClass_DisplayText();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DisplayText DisplayTextParams { get { return s_params_DisplayText; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DisplayText
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string TicketNotificationHtmlEmailTemplate = "TicketNotificationHtmlEmailTemplate";
                public readonly string TicketNotificationOutlookHtmlEmailTemplate = "TicketNotificationOutlookHtmlEmailTemplate";
                public readonly string TicketNotificationTextEmailTemplate = "TicketNotificationTextEmailTemplate";
            }
            public readonly string Index = "~/Areas/Admin/Views/EmailTemplate/Index.aspx";
            public readonly string TicketNotificationHtmlEmailTemplate = "~/Areas/Admin/Views/EmailTemplate/TicketNotificationHtmlEmailTemplate.ascx";
            public readonly string TicketNotificationOutlookHtmlEmailTemplate = "~/Areas/Admin/Views/EmailTemplate/TicketNotificationOutlookHtmlEmailTemplate.ascx";
            public readonly string TicketNotificationTextEmailTemplate = "~/Areas/Admin/Views/EmailTemplate/TicketNotificationTextEmailTemplate.ascx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_EmailTemplateController : TicketDesk.Web.Client.Areas.Admin.Controllers.EmailTemplateController
    {
        public T4MVC_EmailTemplateController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? id, string mode);

        public override System.Web.Mvc.ActionResult Index(int? id, string mode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mode", mode);
            IndexOverride(callInfo, id, mode);
            return callInfo;
        }

        partial void ProcessWaitingNotesNowOverride(T4MVC_System_Web_Mvc_ContentResult callInfo);

        public override System.Web.Mvc.ContentResult ProcessWaitingNotesNow()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.ProcessWaitingNotesNow);
            ProcessWaitingNotesNowOverride(callInfo);
            return callInfo;
        }

        partial void DisplayHtmlOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult DisplayHtml(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DisplayHtml);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DisplayHtmlOverride(callInfo, id);
            return callInfo;
        }

        partial void DisplayOutlookHtmlOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult DisplayOutlookHtml(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DisplayOutlookHtml);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DisplayOutlookHtmlOverride(callInfo, id);
            return callInfo;
        }

        partial void DisplayTextOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult DisplayText(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DisplayText);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DisplayTextOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
