// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace TicketDesk.Web.Client.Controllers
{
    public partial class MarkdownController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MarkdownController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected MarkdownController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ContentResult MarkdownPreview()
        {
            return new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.MarkdownPreview);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MarkdownController Actions { get { return MVC.Markdown; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Markdown";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Markdown";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string MarkdownPreview = "MarkdownPreview";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string MarkdownPreview = "MarkdownPreview";
        }


        static readonly ActionParamsClass_MarkdownPreview s_params_MarkdownPreview = new ActionParamsClass_MarkdownPreview();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MarkdownPreview MarkdownPreviewParams { get { return s_params_MarkdownPreview; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MarkdownPreview
        {
            public readonly string data = "data";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_MarkdownController : TicketDesk.Web.Client.Controllers.MarkdownController
    {
        public T4MVC_MarkdownController() : base(Dummy.Instance) { }

        partial void MarkdownPreviewOverride(T4MVC_System_Web_Mvc_ContentResult callInfo, string data);

        public override System.Web.Mvc.ContentResult MarkdownPreview(string data)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.MarkdownPreview);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            MarkdownPreviewOverride(callInfo, data);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
