// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace TicketDesk.Web.Client.Controllers
{
    public partial class TicketCenterController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected TicketCenterController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult List()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.List);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult FilterList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FilterList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SortList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SortList);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TicketCenterController Actions { get { return MVC.TicketCenter; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "TicketCenter";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "TicketCenter";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string List = "List";
            public readonly string FilterList = "FilterList";
            public readonly string SortList = "SortList";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string List = "List";
            public const string FilterList = "FilterList";
            public const string SortList = "SortList";
        }


        static readonly ActionParamsClass_List s_params_List = new ActionParamsClass_List();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_List ListParams { get { return s_params_List; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_List
        {
            public readonly string page = "page";
            public readonly string listName = "listName";
        }
        static readonly ActionParamsClass_FilterList s_params_FilterList = new ActionParamsClass_FilterList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FilterList FilterListParams { get { return s_params_FilterList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FilterList
        {
            public readonly string listName = "listName";
            public readonly string pageSize = "pageSize";
            public readonly string currentStatus = "currentStatus";
            public readonly string owner = "owner";
            public readonly string assignedTo = "assignedTo";
        }
        static readonly ActionParamsClass_SortList s_params_SortList = new ActionParamsClass_SortList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SortList SortListParams { get { return s_params_SortList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SortList
        {
            public readonly string listName = "listName";
            public readonly string columnName = "columnName";
            public readonly string isMultiSort = "isMultiSort";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string TicketCenter = "TicketCenter";
            }
            public readonly string TicketCenter = "~/Views/TicketCenter/TicketCenter.aspx";
            static readonly _ControlsClass s_Controls = new _ControlsClass();
            public _ControlsClass Controls { get { return s_Controls; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _ControlsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string FilterBar = "FilterBar";
                    public readonly string ListViewMenu = "ListViewMenu";
                    public readonly string TicketList = "TicketList";
                    public readonly string TicketListItem = "TicketListItem";
                }
                public readonly string FilterBar = "~/Views/TicketCenter/Controls/FilterBar.ascx";
                public readonly string ListViewMenu = "~/Views/TicketCenter/Controls/ListViewMenu.ascx";
                public readonly string TicketList = "~/Views/TicketCenter/Controls/TicketList.ascx";
                public readonly string TicketListItem = "~/Views/TicketCenter/Controls/TicketListItem.ascx";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_TicketCenterController : TicketDesk.Web.Client.Controllers.TicketCenterController
    {
        public T4MVC_TicketCenterController() : base(Dummy.Instance) { }

        partial void ListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? page, string listName);

        public override System.Web.Mvc.ActionResult List(int? page, string listName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.List);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "listName", listName);
            ListOverride(callInfo, page, listName);
            return callInfo;
        }

        partial void FilterListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string listName, int pageSize, string currentStatus, string owner, string assignedTo);

        public override System.Web.Mvc.ActionResult FilterList(string listName, int pageSize, string currentStatus, string owner, string assignedTo)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FilterList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "listName", listName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageSize", pageSize);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "currentStatus", currentStatus);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "owner", owner);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "assignedTo", assignedTo);
            FilterListOverride(callInfo, listName, pageSize, currentStatus, owner, assignedTo);
            return callInfo;
        }

        partial void SortListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string listName, string columnName, bool isMultiSort);

        public override System.Web.Mvc.ActionResult SortList(string listName, string columnName, bool isMultiSort)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SortList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "listName", listName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "columnName", columnName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isMultiSort", isMultiSort);
            SortListOverride(callInfo, listName, columnName, isMultiSort);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
